apiVersion: v1
kind: Pod
metadata:
  name: hello-nginx
  labels:
    app: hello-nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-service
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30036
