version: "3.9"

services:
  frontend:
    image: angular-todo-app
    container_name: angular-frontend
    ports:
      - "4200:80"  # Exposes Angular on http://localhost:8080
    restart: unless-stopped

  backend:
    image: todo-app
    container_name: dotnet-backend
    ports:
      - "5000:5000"  # Exposes .NET API on http://localhost:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
