apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-frontend
          image: huynhngocsonuit2000docker/azure-image:angular-todo-app-aks-v3
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
spec:
  type: NodePort
  selector:
    app: angular-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-backend
  template:
    metadata:
      labels:
        app: dotnet-backend
    spec:
      containers:
        - name: dotnet-backend
          image: huynhngocsonuit2000docker/azure-image:todo-app-v3
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-backend-service
spec:
  type: NodePort
  selector:
    app: dotnet-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
